### PR TITLE
Deny illegal host headers for pycon site

### PR DESCRIPTION
**Pull request by ChillarAnand**

### CODE REVIEW

**Comment by ChillarAnand** [comment]
@vigneshsarma  can you reivew?

**Comment by vigneshsarma** [comment]
Can you tell me how to replicate this issue?

**Comment by vigneshsarma** [comment]
I tried this, 

```
curl -k -v -H'Host: foo' https://205.147.96.46:443/2016/
```

didn't throw any errors.

**Comment by ChillarAnand** [comment]
We were getting emails for illegal hosts, that's why I created this.

**Pull request closed without merging**
